### ISSUE TITLE
Issue regarding eta and log file

### ISSUE THREAD

**Issue by deadman36g** [citizen428/unsavory-legacy#11]
Hello,

I enjoy using your unsavory app but I do have a few questions.

I have installed using "sudo gem install unsavory” but I am missing a few options

1. I do not see an eta when running unsavory

2. Running using the -l parameter is not creating a log file for me. I have since found that the log is created by running for example -lunsavory.log. I find it confusing that a space between -l and the actual location creates an error

The installed version I have is listed as unsavory-1.4

**Comment by citizen428** [comment]
Please note that the Ruby version of `unsavory` will be discontinued. All future development will be on the [Golang version](https://github.com/citizen428/unsavory) (they don't have feature parity yet).
